<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
      <ProjectReference Include="..\Stayza.Application\Stayza.Application.csproj" />
      <ProjectReference Include="..\Stayza.Infrastructure\Stayza.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
      <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" />
      <PackageReference Include="AspNetCore.HealthChecks.Uris" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
      <PackageReference Include="O9d.AspNet.FluentValidation" />
      <PackageReference Include="Swashbuckle.AspNetCore" />
      <PackageReference Include="Swashbuckle.AspNetCore.Filters" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Infrastructure\ExceptionHandlers\Books\" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
