<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Stayza.Core\Stayza.Core.csproj" />
      <ProjectReference Include="..\Stayza.Infrastructure\Stayza.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
