version: '3.8'
services:
  structurizr:
    image: structurizr/lite
    container_name: documentation
    ports:
      - "9090:8080"
    volumes:
      - ./docs/architecture:/usr/local/structurizr
    restart: unless-stopped