services:
  postgres:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 5s
      timeout: 3s
      retries: 5
   
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # Management plugin port
    environment:
      RABBITMQ_DEFAULT_USER: guest1
      RABBITMQ_DEFAULT_PASS: guest1
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s #adjust inside the runners
      timeout: 30s
      retries: 3  
    
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379" # Redis default port
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
  
  notifications_api:
    container_name: notifications_api
    image: notifications_api
    build:
      context: .
      dockerfile: ./src/Notifications.Web/Dockerfile
    ports:
      - "1000:80"
      - "1001:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: TEST
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
        
  stayza_api:
    container_name: stayza_api
    image: stayza_api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      notifications_api:
        condition: service_started
    build:
      context: .
      dockerfile: ./src/Stayza.Web/Dockerfile
    ports:
      - "5210:80"
      - "5211:443"
    environment:
      ASPNETCORE_URLS: https://+:443;http://+:80
      Notifications__Url: http://notifications_api:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: TEST
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      OpenTelemetrySettings__TracesEndpoint: "http://otel-collector:4317"
      RabbitMQSettings__ConnectionString: "amqp://guest1:guest1@rabbitmq:5672/"
      ExternalConfigurationOptions__Enabled: false
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"
    volumes:
      - ~/.aspnet/https:/https:ro
  
volumes:
  postgres_data:
  pgadmin_data: