services:  
  postgres:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
   
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # Management plugin port
    environment:
      RABBITMQ_DEFAULT_USER: guest1
      RABBITMQ_DEFAULT_PASS: guest1

  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379" # Redis default port
  
  notifications_api:
    container_name: notifications_api
    image: notifications_api
    build:
      context: .
      dockerfile: ./src/Notifications.Web/Dockerfile
    ports:
      - "1000:80"
      - "1001:443"
    environment: #https://learn.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-9.0 -> tutorial on generating certificates
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: TEST
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    
volumes:
  postgres_data: