// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stayza.Infrastructure.Persistence;

#nullable disable

namespace Stayza.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stayza.Domain.BookAggregate.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0c22377-4fe9-4d95-89bb-61f498c8c1be"),
                            Author = "Juval Löwy",
                            ISBN = "9781642955706",
                            Title = "Righting Software"
                        },
                        new
                        {
                            Id = new Guid("6106dfed-7f89-43f0-8a5d-22775be15211"),
                            Author = "Gregor Hohpe, Bobby Woolf",
                            ISBN = "9780321200686",
                            Title = "Enterprise Integration Patterns"
                        },
                        new
                        {
                            Id = new Guid("c5e0a48f-9bcc-4e39-8474-81df953756a2"),
                            Author = "Gregor Hohpe",
                            ISBN = "9781642955706",
                            Title = "The Architect's Elevator"
                        },
                        new
                        {
                            Id = new Guid("cb295459-2d9f-40ef-b423-62375b5db562"),
                            Author = "Vlad Khononov",
                            ISBN = "9781617298413",
                            Title = "Balancing Coupling in Software Design"
                        },
                        new
                        {
                            Id = new Guid("61415c09-6dd2-42d8-a1e4-03774558a4b5"),
                            Author = "Andrew Hunt, David Thomas",
                            ISBN = "9780135957059",
                            Title = "The Pragmatic Programmer"
                        });
                });

            modelBuilder.Entity("Stayza.Domain.BookCopyAggregate.BookCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95ea8f22-ad65-4278-ba50-eb96af41397e"),
                            BookId = new Guid("e0c22377-4fe9-4d95-89bb-61f498c8c1be"),
                            IsRetired = false
                        },
                        new
                        {
                            Id = new Guid("16d7bbf1-474d-4036-a81b-e3ce0b64a361"),
                            BookId = new Guid("6106dfed-7f89-43f0-8a5d-22775be15211"),
                            IsRetired = false
                        },
                        new
                        {
                            Id = new Guid("f0d7cdc7-8fe1-4a5f-9ac3-94ae0587d9a5"),
                            BookId = new Guid("c5e0a48f-9bcc-4e39-8474-81df953756a2"),
                            IsRetired = false
                        },
                        new
                        {
                            Id = new Guid("535e94c0-e2e9-4375-8f48-3caf42e5f58c"),
                            BookId = new Guid("cb295459-2d9f-40ef-b423-62375b5db562"),
                            IsRetired = false
                        },
                        new
                        {
                            Id = new Guid("2c80e65f-f8a5-4c2f-84a0-773fd71293b5"),
                            BookId = new Guid("61415c09-6dd2-42d8-a1e4-03774558a4b5"),
                            IsRetired = false
                        });
                });

            modelBuilder.Entity("Stayza.Domain.BookCopyAggregate.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookCopyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Stayza.Domain.BookCopyAggregate.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookCopyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Stayza.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Stayza.Domain.BookCopyAggregate.BookCopy", b =>
                {
                    b.HasOne("Stayza.Domain.BookAggregate.Book", null)
                        .WithMany("Copies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stayza.Domain.BookCopyAggregate.Loan", b =>
                {
                    b.HasOne("Stayza.Domain.UserAggregate.User", null)
                        .WithMany("ExistingLoans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Stayza.Domain.BookCopyAggregate.TimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<Guid>("LoanId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("LoanId");

                            b1.ToTable("Loans");

                            b1.WithOwner()
                                .HasForeignKey("LoanId");
                        });

                    b.Navigation("TimeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Stayza.Domain.BookCopyAggregate.Reservation", b =>
                {
                    b.HasOne("Stayza.Domain.BookCopyAggregate.BookCopy", null)
                        .WithMany("ActiveReservations")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stayza.Domain.UserAggregate.User", null)
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stayza.Domain.BookAggregate.Book", b =>
                {
                    b.Navigation("Copies");
                });

            modelBuilder.Entity("Stayza.Domain.BookCopyAggregate.BookCopy", b =>
                {
                    b.Navigation("ActiveReservations");
                });

            modelBuilder.Entity("Stayza.Domain.UserAggregate.User", b =>
                {
                    b.Navigation("ExistingLoans");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
