name: "PR Verify"
on:
    pull_request: 
        branches: [ "main" ]
    
jobs:
    build:
        name: PR Verify
        runs-on: ubuntu-latest
        steps:

        -   name: Checkout code
            uses: actions/checkout@v4

        -   name: Setup .NET
            uses: actions/setup-dotnet@v4
            # with:
            #     dotnet-version: 8.x
            #     dotnet-quality: 'ga'

        -   name: Restore dependencies
            run: dotnet restore

        -   name: Build
            run: dotnet build --no-restore

        -   name: Run unit tests
            run: dotnet test tests/Stayza.Tests.Unit/Stayza.Tests.Unit.csproj --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage"

        # -   name: Run API layer integration tests
        #     run: dotnet test tests/Stayza.Tests.Integration/Stayza.Tests.Integration.csproj --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage"

        # -   name: "Run subcutaneous layer integration tests"
        #     run: dotnet test tests/Stayza.Tests.Subcutaneous/Stayza.Tests.Subcutaneous.csproj --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage"

        # -   name: Run contract tests
        #     run: dotnet test tests/Stayza.Tests.Contract/Stayza.Tests.Contract.csproj --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage"

            # Tool by: https://github.com/danielpalme/ReportGenerator
            # Tips here: https://reportgenerator.io/usage
        # -   name: Install report generator
        #     run: dotnet tool install --global dotnet-reportgenerator-globaltool

        # -   name: Install gitversion
        #     run: dotnet tool install --global GitVersion.Tool --version 5.10.1

        -   name: Add .NET tools to PATH
            run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

        -   name: Determine semantic version
            id: gitversion
            run: |
                dotnet tool restore
                echo "Running GitVersion..."
                SEMVER=$(dotnet dotnet-gitversion /showvariable SemVer)
                echo "Semantic version: $SEMVER"
                echo "semver=$SEMVER" >> $GITHUB_OUTPUT

        -   name: Example usage of semantic version
            run: echo "Current semantic version is ${{ steps.gitversion.outputs.semver }}"

        -   name: Combine coverage reports
            run: |
                mkdir -p coveragereport
                reportgenerator \
                "-reports:**/*.cobertura.xml" \
                "-targetdir:coveragereport" \
                "-reporttypes:HtmlInline;Cobertura;MarkdownSummaryGithub" \
                "-verbosity:Info" \
                "-title:Code Coverage" \
                "-tag:${{ github.run_number }}_${{ github.run_id }}" \
                "-toolpath:reportgeneratortool"

        -   name: Print markdown Summary
            run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

        -   name: Upload test result files
            uses: actions/upload-artifact@v4
            with:
                name: test-results
                path: ${{ github.workspace }}/**/TestResults/**/*
                retention-days: 2

        -   name: Upload generated reports
            uses: actions/upload-artifact@v4
            with:
                name: test-reports
                path: ${{ github.workspace }}/coveragereport
                retention-days: 2


                